version: '3.8'

services:
  mysql:
    image: mysql:8.0.39
    container_name: mysql_eventmaster
    ports:
      - "3308:3306" 
    volumes:
      - eventmaster_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pwd
      - MYSQL_DATABASE=eventmaster
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pwd
    command: --default-authentication-plugin=mysql_native_password

volumes:
  eventmaster_db:
